name: dmutility
description: "DMUtility"
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freefeos:
    path: ../../FlutterProjects/freefeos
  multi_builder: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.wyq0918dev.dmutility.flutter
